version: 1

rules:
  - expected: 安定版
    pattern:  安定板 # 2021年版本番稿の誤植、迷惑かけた

  - expected: Org-mode
    patterns:
      - /org-mode/
      - /Org-Mode/
      - orgmode

  # 本書では「パソコン」で統一
  # tech-word からのリンティング指摘は無視
  - expected: パソコン
    patterns:
      - PC
      - コンピュータ
      - コンピューター

  # 本書では「MacOS」で統一
  - expected: MacOS
    patterns:
      - macOS
      - Mac OS

  # Emacs利用者だけに通じる言葉は使わない
  - expected: キーボードショートカット
    patterns:
      - キーバインド
      - キーバインディング
