version: 1

rules:
  - expected: 安定版
    pattern:  安定板 # 2021年版本番稿の誤植、迷惑かけた

  - expected: Org Mode
    patterns:
      - /org-mode/
      - /Org-mode/
      - /Org-Mode/
      - orgmode

  # 本書では「パソコン」で統一
  # tech-word からのリンティング指摘は無視
  - expected: パソコン
    patterns:
      - PC
      - コンピュータ
      - コンピューター

  - expected: ユーザー
    patterns:
      - ユーザ
      - 利用者

  # 本書では「MacOS」で統一
  - expected: MacOS
    patterns:
      - macOS
      - Mac OS

  - expected: マークダウン
    patterns: Markdown

  # Emacs用語は使わない
  - expected: キーボードショートカット
    patterns:
      - キーバインド
      - キーバインディング

  - expected: カット
    patterns:
      - キル
      - kill

  - expected: ペースト
    patterns:
      - ヤンク
      - yank

  # アウトライナー系用語の統一
  - expected: ズーム
    patterns:
      - zoom
      - ナロー
      - narrow
      - フォーカス
